services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: ${APP_DB_NAME}
      DB_USER: root
      DB_PASSWORD: ${APP_DB_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: bookstore_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3307:3306"
    restart: unless-stopped

volumes:
  db_data: