<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Author List</title>
    <link rel="stylesheet" href="../style/tables.css">
</head>
<body>
<div class="container">
    <table>
        <thead>
        <tr>
            <th class="author-col">Author</th>
            <th class="books-col">Books</th>
            <th class="actions-col">Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($authors as $author): ?>
            <tr>
                <td>
                    <div class="author-name">
                        <div class="user-image">
                            <img src="/images/user.png" alt="user">
                        </div>
                        <a href="pages/booklist.html?author_id=<?= $author['id'] ?>">
                            <b><?= htmlspecialchars($author['name']) ?></b>
                        </a>
                    </div>
                </td>
                <td class="books-col">
                    <div class="book-count">0</div>
                </td>
                <td class="actions-col">
                    <div class="actions">
                        <a class="button edit" href="/src/index.php?action=editAuthor&id=<?= $author['id'] ?>">
                            <img src="../images/pen.png" alt="pen">
                        </a>
                        <a class="button delete" href="/src/index.php?action=deleteAuthor&id=<?= $author['id'] ?>">
                            <img src="../images/minus.png" alt="minus">
                        </a>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div class="add-container">
    <a class="add" href="/src/index.php?action=createAuthor">
        <img src="../images/add.png" alt="add" class="add-image">
    </a>
</div>
</body>
</html>
